name: Assignment3 Workflow

on:
  push:

  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        #credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        workload_identity_provider: 'projects/1091651802363/locations/global/workloadIdentityPools/github-iden-pool/providers/my-provider'
        service_account: 'github-action-service-account@cs7346-assignment3.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Submit to Cloud Build'
      run: gcloud builds submit --tag gcr.io/cs7346-assignment3/7346_assignment3

    - name: 'Deploy to Cloud Run'
      run: gcloud run deploy assignment3-simple-webserver --image=gcr.io/cs7346-assignment3/7346_assignment3:latest --region=us-central1 --allow-unauthenticated


      
      
      
      
